# Generated by Django 6.0.3 on 2026-07-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_django_rakaia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_id", models.CharField(max_length=64)),
                ("version", models.IntegerField()),
                ("marker", models.CharField(max_length=1)),
                ("actor", models.IntegerField(blank=True, null=True)),
                ("ts", models.FloatField(default=0)),
                ("snapshot", models.JSONField(default=dict)),
            ],
            options={
                "unique_together": {("submission_id", "version")},
            },
        ),
    ]
