# Generated by Django 6.0.3 on 2026-08-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_django_rakaia", "0007_archiveddoc_softdeletedoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="observed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="observed_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
