# Generated by Django 6.0.3 on 2026-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_django_rakaia", "0008_measure_observed_at_measure_observed_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeaterProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_id", models.UUIDField(unique=True)),
                ("parent_id", models.UUIDField()),
                ("status_id", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_id", models.UUIDField(unique=True)),
                ("status_id", models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
