# Generated by Django 6.0.3 on 2026-10-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rakaia", "0013_event_tags_and_correlation"),
        ("test_django_rakaia", "0010_coverage_rows"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="django_rakaia.streamevent",
                    ),
                ),
            ],
        ),
    ]
