# Generated by Django 6.0.3 on 2026-07-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersummary",
            name="bonus_points",
            field=models.IntegerField(default=0),
        ),
    ]
