"""What a read answers with, decided once for both forms of read.

The twin of `rakaia.append_decision`, and deliberately the same shape: facts in,
a verdict out, no store and no `send` anywhere. `decide_append` is to
`WritableStore.append` what the functions here are to `_handle_read` — the
protocol semantics lifted out of the code that performs I/O, so the rules can be
asked a question instead of observed through a socket.

**What a read decides.** Six things, and every one of them used to be decided
part-way through a ~190-line function with eight `send_response` exits:

1. the offset to report (the last message's, or the stream's tail),
2. whether the client is at the tail,
3. whether the answer is up to date,
4. whether the stream is closed *as far as this response is concerned*,
5. what to cache against — the ETag, and whether to answer 304 instead,
6. what the body is (formatted messages, `[]`, or nothing).

**Two callers, one answer.** The plain read (`GET`) and the live push (SSE)
answer all six for the same stream. They used to answer them separately:
`_handle_read` required `up_to_date` before reporting closure, `_build_sse_control`
did not. Neither store in this repository can return `up_to_date=False`, so the
two never gave different answers in practice — but they were two rules, and only
one of them was reachable from a test without a socket. `closed_at_tail` is now
the only place that rule is written, and `tests/test_rakaia/test_read_decision.py`
asserts the header and the SSE control field agree for the same facts.

**Termination is a separate rule from the header**, which is why `stream_ended`
exists next to `closed_at_tail` rather than being folded into it. The live push
must stop looping on a closed stream at the tail whatever `up_to_date` says;
folding the two together would let a store that reported `up_to_date=False` spin
forever.

**No clock and no randomness.** Response cursors are generated by the caller and
handed in (`response_cursor`), so every verdict here is a pure function of its
arguments and every test is deterministic. `None` means *omit the header*, which
is what the immediate closed-at-tail exit has always done.

**Quirks are preserved, not tidied**, because this is a shape change and nothing
else. Two are worth naming, both now pinned by tests rather than latent: a `304`
carries only its ETag and no CORS headers, and the immediate closed-at-tail `204`
carries no `Stream-Cursor` where the two post-wait exits do.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass, field

from .json_mode import is_json_content_type
from .types import (
    SSE_CLOSED_FIELD,
    SSE_CURSOR_FIELD,
    SSE_OFFSET_FIELD,
    SSE_UP_TO_DATE_FIELD,
    VALID_OFFSET_PATTERN,
)

# Response header names, title-cased by HTTP convention. `rakaia.types` holds
# the lower-case wire names used for *reading* request headers; these are the
# spellings rakaia emits.
STREAM_OFFSET_HEADER_RESP = "Stream-Next-Offset"
STREAM_CURSOR_HEADER_RESP = "Stream-Cursor"
STREAM_UP_TO_DATE_HEADER_RESP = "Stream-Up-To-Date"
STREAM_CLOSED_HEADER_RESP = "Stream-Closed"
STREAM_TTL_HEADER_RESP = "Stream-TTL"
STREAM_EXPIRES_AT_HEADER_RESP = "Stream-Expires-At"


@dataclass(frozen=True)
class ReadFacts:
    """What the decision needs to know about a stream, with no store attached.

    A deliberately small surface: whatever a backend holds, these are the only
    fields a read response is built from. The same type describes the stream as
    first fetched and as re-fetched just before the response is built — see
    `decide_read`, which takes both, because the tail can move (or the stream can
    vanish) in between.
    """

    path: str
    tail_offset: str
    closed: bool = False
    content_type: str | None = None
    ttl_seconds: int | None = None
    expires_at: str | None = None


@dataclass(frozen=True)
class ReadRequest:
    """What the client asked for. Raw query values, not normalised.

    `offset` is the parameter as sent — including the literal ``"now"``, which is
    what the ETag is keyed on, so normalising it here would change what clients
    cache against.
    """

    offset: str | None = None
    live: str | None = None
    if_none_match: str | None = None


@dataclass(frozen=True)
class ReadVerdict:
    """A response, worked out but not sent.

    `body` is the bytes to send, or `None` meaning *the caller formats the
    messages* — that is the one part of a read the store owns (JSON framing) and
    the only reason a verdict is not the whole answer.
    """

    status: int
    headers: dict[str, str] = field(default_factory=dict)
    body: bytes | None = b""


def closed_at_tail(*, closed: bool, at_tail: bool, up_to_date: bool) -> bool:
    """Whether this response should tell the client the stream is closed.

    All three conditions matter. Closed-but-behind must not be reported as
    closed: the client still has messages to fetch, and a `Stream-Closed` would
    tell it to stop. Not up to date is the same case seen from the store's side.

    The only rule in the codebase for this, used by the plain read's
    `Stream-Closed` header, its ETag `:c` suffix, and the live push's
    `streamClosed` control field.
    """
    return closed and at_tail and up_to_date


def stream_ended(*, closed: bool, at_tail: bool) -> bool:
    """Whether the live push should stop looping.

    Deliberately *not* `closed_at_tail`: this is a liveness rule, not a header
    rule. A closed stream at its tail will never produce another message, so
    waiting on one cannot terminate — regardless of what `up_to_date` says.
    """
    return closed and at_tail


def read_etag(
    path: str,
    *,
    start_offset: str,
    response_offset: str,
    closed: bool = False,
) -> str:
    """The ETag for a read: ``"{path_b64}:{from}:{to}[:c]"``, quoted.

    Written once for `GET` and `HEAD`. A `HEAD` has no request offset, so it
    passes ``-1`` and its own tail; that is why `HEAD` and `GET` can share this
    despite one of them having no client position at all.

    `closed` is the `closed_at_tail` verdict, not the stream's raw flag — the
    suffix has to move with the header, or a client would cache a body under a
    key that disagrees with what it was told about closure.
    """
    path_b64 = base64.b64encode(path.encode()).decode()
    suffix = ":c" if closed else ""
    return f'"{path_b64}:{start_offset}:{response_offset}{suffix}"'


def read_param_error(
    *,
    offset: str | None,
    live: str | None,
    offset_count: int = 1,
) -> tuple[int, bytes] | None:
    """The response a malformed read request becomes, or `None` if it is fine.

    Four of the eight exits from `_handle_read`, in the order they are checked —
    the order is observable, since a request can be wrong in more than one way at
    once and only the first refusal is sent.

    `offset_count` is how many `offset` parameters the query string carried; only
    the store's own request parsing knows that, so it is passed in.
    """
    if offset is not None:
        if offset == "":
            return 400, b"Empty offset parameter"
        if offset_count > 1:
            return 400, b"Multiple offset parameters not allowed"
        if not VALID_OFFSET_PATTERN.match(offset):
            return 400, b"Invalid offset format"

    # Long-poll and SSE both require an explicit offset: without one there is no
    # position to wait from.
    if live in ("long-poll", "sse") and not offset:
        label = "SSE" if live == "sse" else "Long-poll"
        return 400, f"{label} requires offset parameter".encode()

    return None


def decide_head(facts: ReadFacts, *, cors: dict[str, str] | None = None) -> ReadVerdict:
    """Stream metadata, no body.

    `no-store`, because the answer is the stream's current tail and that changes
    on every append. The expiry metadata is reported but not extended: a `HEAD`
    is not activity on the stream.
    """
    headers: dict[str, str] = {
        **(cors or {}),
        STREAM_OFFSET_HEADER_RESP: facts.tail_offset,
        "cache-control": "no-store",
    }
    if facts.content_type:
        headers["content-type"] = facts.content_type
    if facts.closed:
        headers[STREAM_CLOSED_HEADER_RESP] = "true"
    if facts.ttl_seconds is not None:
        headers[STREAM_TTL_HEADER_RESP] = str(facts.ttl_seconds)
    if facts.expires_at:
        headers[STREAM_EXPIRES_AT_HEADER_RESP] = facts.expires_at
    # A HEAD is by definition at the tail and up to date, so the stream's raw
    # closed flag *is* the closed-at-tail verdict here.
    headers["etag"] = read_etag(
        facts.path,
        start_offset="-1",
        response_offset=facts.tail_offset,
        closed=facts.closed,
    )
    return ReadVerdict(200, headers)


def decide_catch_up(
    facts: ReadFacts, *, cors: dict[str, str] | None = None
) -> ReadVerdict:
    """``?offset=now`` on a plain read: nothing to send, here is where you are.

    An empty answer still has to be well-formed for the content type, so a JSON
    stream gets ``[]`` and anything else gets no bytes at all. No ETag: there is
    nothing to cache, and the offset it would name is stale the moment an append
    lands.
    """
    headers: dict[str, str] = {
        **(cors or {}),
        STREAM_OFFSET_HEADER_RESP: facts.tail_offset,
        STREAM_UP_TO_DATE_HEADER_RESP: "true",
        "cache-control": "no-store",
    }
    if facts.content_type:
        headers["content-type"] = facts.content_type
    if facts.closed:
        headers[STREAM_CLOSED_HEADER_RESP] = "true"
    body = b"[]" if is_json_content_type(facts.content_type) else b""
    return ReadVerdict(200, headers, body)


def decide_wait_ended(
    *,
    response_offset: str,
    closed: bool,
    response_cursor: str | None,
    cors: dict[str, str] | None = None,
) -> ReadVerdict:
    """A long-poll that ended with nothing to deliver: `204`, no body.

    Three exits share this. `response_cursor=None` omits `Stream-Cursor`, which
    is what the exit taken *before* waiting has always done — the two exits taken
    after waiting send one. Preserved rather than harmonised: this is a shape
    change, and a client that gets no cursor simply does not collapse.

    `closed` is passed rather than derived because each exit knows it from a
    different place: the stream as fetched, the wait's own signal, or a re-fetch
    after the timeout.
    """
    headers: dict[str, str] = {
        **(cors or {}),
        STREAM_OFFSET_HEADER_RESP: response_offset,
        STREAM_UP_TO_DATE_HEADER_RESP: "true",
    }
    if response_cursor is not None:
        headers[STREAM_CURSOR_HEADER_RESP] = response_cursor
    if closed:
        headers[STREAM_CLOSED_HEADER_RESP] = "true"
    return ReadVerdict(204, headers)


def decide_read(
    facts: ReadFacts,
    request: ReadRequest,
    *,
    latest: ReadFacts | None,
    last_message_offset: str | None,
    up_to_date: bool,
    response_cursor: str | None = None,
    cors: dict[str, str] | None = None,
) -> ReadVerdict:
    """The answer to a read that has messages (or is simply at the tail).

    `facts` is the stream as first fetched; `latest` is it re-fetched after the
    messages were read, or `None` if it has since gone. Both are needed and they
    are not interchangeable: the content type comes from the first, closure and
    the tail from the second, because an append or a close landing mid-read must
    not be reported as closed-at-tail against a stale tail.

    A `304` deliberately carries only its ETag — no CORS, no other header. That
    is what the handler has always sent; it is written here so that it is a
    tested fact rather than an accident of where the `return` sat.
    """
    response_offset = (
        last_message_offset if last_message_offset is not None else facts.tail_offset
    )
    at_tail = latest is not None and response_offset == latest.tail_offset
    closed = closed_at_tail(
        closed=latest is not None and latest.closed,
        at_tail=at_tail,
        up_to_date=up_to_date,
    )

    headers: dict[str, str] = {**(cors or {})}
    if facts.content_type:
        headers["content-type"] = facts.content_type
    headers[STREAM_OFFSET_HEADER_RESP] = response_offset
    if request.live == "long-poll" and response_cursor is not None:
        headers[STREAM_CURSOR_HEADER_RESP] = response_cursor
    if up_to_date:
        headers[STREAM_UP_TO_DATE_HEADER_RESP] = "true"
    if closed:
        headers[STREAM_CLOSED_HEADER_RESP] = "true"

    etag = read_etag(
        facts.path,
        start_offset=request.offset or "-1",
        response_offset=response_offset,
        closed=closed,
    )
    headers["etag"] = etag

    if request.if_none_match and request.if_none_match == etag:
        return ReadVerdict(304, {"etag": etag})

    return ReadVerdict(200, headers, body=None)


def sse_control_fields(
    *,
    control_offset: str,
    tail_offset: str,
    closed: bool,
    up_to_date: bool,
    response_cursor: str,
) -> dict[str, str | bool]:
    """The live push's answer to the same six questions, as control-event fields.

    The field names differ from the header names and the encoding differs, but
    the rules are the ones above: `closed_at_tail` decides `streamClosed`, and a
    frame that is not closed-at-tail carries a cursor instead, plus `upToDate`
    when it is the tail.

    Closure and a cursor are mutually exclusive by design — a consumer that has
    been told the stream is closed has nothing left to collapse.
    """
    at_tail = control_offset == tail_offset
    fields: dict[str, str | bool] = {SSE_OFFSET_FIELD: control_offset}
    if closed_at_tail(closed=closed, at_tail=at_tail, up_to_date=up_to_date):
        fields[SSE_CLOSED_FIELD] = True
    else:
        fields[SSE_CURSOR_FIELD] = response_cursor
        if at_tail and up_to_date:
            fields[SSE_UP_TO_DATE_FIELD] = True
    return fields
