# Generated by Django 5.2.12 on 2026-03-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rakaia_stream',
                'ordering': ['stream_id'],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'rakaia_streamevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='django_rakaia.stream')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='django_rakaia.streamevent')),
            ],
            options={
                'db_table': 'rakaia_streamentry',
                'ordering': ['stream', 'offset'],
                'indexes': [models.Index(fields=['stream', 'offset'], name='rakaia_stre_stream__e1ca6a_idx'), models.Index(fields=['stream', '-offset'], name='rakaia_stre_stream__a7b9a3_idx')],
                'unique_together': {('stream', 'offset')},
            },
        ),
    ]
