# Generated by Django 6.0.3 on 2026-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rakaia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
