# Generated by Django 6.0.3 on 2026-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rakaia", "0003_consumercursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamevent",
            name="event_ts",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
