# Generated by Django 6.0.3 on 2026-07-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rakaia", "0004_streamevent_event_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamOffsetWatermark",
            fields=[
                (
                    "stream_path",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("high", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "rakaia_streamoffsetwatermark",
            },
        ),
    ]
