# Generated by Django 6.0.3 on 2026-08-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rakaia", "0006_alter_streamevent_data_alter_streamevent_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stream",
            name="closed_at",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="closed_by_epoch",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="closed_by_producer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="closed_by_seq",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="content_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="expires_at",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="last_activity_at",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="stream",
            name="last_seq",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stream",
            name="ttl_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StreamProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producer_id", models.CharField(max_length=255)),
                ("epoch", models.IntegerField()),
                ("last_seq", models.IntegerField()),
                ("last_updated", models.FloatField()),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producers",
                        to="django_rakaia.stream",
                    ),
                ),
            ],
            options={
                "db_table": "rakaia_streamproducer",
                "unique_together": {("stream", "producer_id")},
            },
        ),
    ]
