# Generated by Django 6.0.3 on 2026-08-15 04:30

from django.db import migrations


class Migration(migrations.Migration):
    """Remove the `Translatable` demo model from the library.

    `django_rakaia` shipped a translations model, admin, HTMX dashboard and SSE
    endpoint — demo domain, not library surface, and its `langcode` choices were
    Timor-Leste specific. Because it was in `0001_initial`, **every** consumer
    got the table whether or not they ever used it. It has moved to
    `examples/polyglot`, which is the only thing that ever used it.

    This **drops the table**. If you have rows in `django_rakaia_translatable`,
    copy them out before migrating — see UPGRADING.md, which also carries the
    model definition to paste into your own app if you were relying on it.
    """

    dependencies = [
        ("django_rakaia", "0007_stream_closed_stream_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translatable",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="translatable",
            name="django_raka_msgid_c76e21_idx",
        ),
        migrations.DeleteModel(
            name="Translatable",
        ),
    ]
