# Generated by Django 6.0.3 on 2026-09-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rakaia", "0009_alter_stream_last_seq"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer", models.CharField(max_length=128)),
                ("stream_path", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("offset", models.CharField(max_length=64, null=True)),
                ("sequence_key", models.CharField(max_length=255)),
                ("stage", models.CharField(max_length=16)),
                ("status", models.CharField(max_length=16)),
                ("reasons", models.JSONField(default=list)),
                ("params", models.JSONField(default=dict)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rakaia_eventoutcome",
                "unique_together": {("consumer", "stream_path", "subject", "attempt")},
            },
        ),
    ]
