# Generated by Django 6.0.3 on 2026-10-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Tags and a business correlation id on each event.

    Both additive, and nothing is backfilled: existing events read back with no
    tags and no correlation id. Adding the column is instant (nullable, no
    default); building its index scans the event table once.
    """

    dependencies = [
        ("django_rakaia", "0012_streamoffsetwatermark_last_event_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamEventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "rakaia_streameventtag",
            },
        ),
        migrations.AddField(
            model_name="streamevent",
            name="correlation_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="streamevent",
            index=models.Index(
                fields=["correlation_id"], name="rakaia_event_correlation"
            ),
        ),
        migrations.AddField(
            model_name="streameventtag",
            name="event",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="django_rakaia.streamevent",
            ),
        ),
        migrations.AddIndex(
            model_name="streameventtag",
            index=models.Index(fields=["tag"], name="rakaia_streameventtag_tag"),
        ),
        migrations.AddConstraint(
            model_name="streameventtag",
            constraint=models.UniqueConstraint(
                fields=("event", "tag"), name="rakaia_streameventtag_unique"
            ),
        ),
    ]
