# Generated by Django 6.0.3 on 2026-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=16, unique=True)),
                ("closed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["period"],
            },
        ),
        migrations.CreateModel(
            name="Suku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProgressRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suku", models.CharField(max_length=64)),
                ("output", models.CharField(max_length=32)),
                ("period", models.CharField(max_length=16)),
                ("percent", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["suku", "output", "period"],
                "unique_together": {("suku", "output", "period")},
            },
        ),
    ]
