# Generated by Django 6.0.3 on 2026-08-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translatable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msgid",
                    models.CharField(
                        help_text="The original message to be translated",
                        max_length=2048,
                    ),
                ),
                (
                    "msgstr",
                    models.CharField(
                        blank=True,
                        help_text="Translated message",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Message domain",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "msgctxt",
                    models.CharField(
                        blank=True,
                        help_text="Message context",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "langcode",
                    models.CharField(
                        choices=[("tet", "tet"), ("pt", "pt"), ("id", "id")],
                        default="en",
                        help_text="The destination language code",
                        max_length=3,
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["msgid", "msgctxt", "langcode"],
                        name="polyglot_tr_msgid_67af6d_idx",
                    )
                ],
                "unique_together": {("msgid", "msgctxt", "langcode")},
            },
        ),
    ]
